# todo change to MP?
# todo implement service discovery
# todo implement declarative client
# todo process objects with json-p
# todo fix test - disable consul
# todo move to .conf
server:
  port: 8081

application-info:
  name: helidon-service
  framework:
    name: Helidon SE
    release-year: 2019
